### ISSUE TITLE
Optimize text search performance

### ISSUE THREAD

**Issue by AdeBC** [BigDataBiology/AMPSphereWebsite#12]

**Comment by AdeBC** [comment]
This package helped me a lot: https://sqlite-utils.datasette.io/en/stable/

**Comment by AdeBC** [comment]
To enable FTS: 
`sqlite-utils enable-fts ampsphere_main_db/AMPSphere_v.2021-03.sqlite Metadata \
GMSC sample microbial_source specI geographic_location general_envo_name`

To test if it works:
`sqlite-utils search ampsphere_main_db/AMPSphere_v.2021-03.sqlite Metadata soil`

**Comment by luispedro** [comment]
Maybe this can be close?

**Comment by AdeBC** [comment]
Yes. Later if we want to have this feature we can reopen this anyway.
