### ISSUE TITLE
Sequence downloads not working

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/AMPSphereWebsite#34]
**Describe the bug**

Downloading sphere files results in a redirect to 127.0.0.1 (which then fails).

**To Reproduce**
1. Go to https://ampsphere.big-data-biology.org/family?accession=SPHERE-III.002_399
2. Click on `Downloads` tab
2. Click on any of the _Download_ links

**Expected behavior**

Download a file

**Desktop (please complete the following information):**
Chrome on Linux

**Comment by AdeBC** [comment]
Should be fixed now, see https://github.com/BigDataBiology/AMPSphereBackend/pull/4.
