### ISSUE TITLE
Show HMM logo for each family (if available)

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/AMPSphereWebsite#38]
**Is your feature request related to a problem? Please describe.**

For example, the page
https://ampsphere.big-data-biology.org/family?accession=SPHERE-III.003_141

could have the logo

**Describe the solution you'd like**

See the logo.

**Comment by celiosantosjr** [comment]
The HMMLogo and SeqLogo are available for download.
Do you mean explicitly showing it on the family page?

**Comment by luispedro** [comment]
Frankly, I don't see as much point in downloading them as in showing them.

**Comment by AdeBC** [comment]
After some discussion with Celio, I removed all HMM logos and only display sequence logo on the family page.

I think we can also make it downloadable as SVG file if needed (#37).
