### ISSUE TITLE
Download CSV in Browser page leads to unnecessary large file

### ISSUE THREAD

**Issue by celiosantosjr** [BigDataBiology/AMPSphereWebsite#41]
**Description**
The CSV downloaded from the Browse page is unnecessarily large and the format is not CSV-friendly at all. Maybe selecting just some of the columns and the sequences per page makes a better result, or at least, provides a more readily parsed file.

**To Reproduce**
1. Go to 'Browse'
2. Click on 'Download CSV'

**Expected behavior**
A better format for the CSV file, easier to parse, and virtually smaller in size.

**Screenshots**
![image](https://user-images.githubusercontent.com/19297744/162977710-e1f1c8d8-7205-45e8-80a9-ed67db807742.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Comment by AdeBC** [comment]
Thanks! 

I've removed all json data in the csv table on our dev webpage.
