### ISSUE TITLE
Current example search leads to no results and bad message

### ISSUE THREAD

**Issue by luispedro** [BigDataBiology/AMPSphereWebsite#42]
To reproduce, just click _SUBMIT_ on the front page. There is nothing returned.

![image](https://user-images.githubusercontent.com/79334/163020963-5658b5f7-2d04-4cd6-b89b-dae1d366569b.png)

**Comment by AdeBC** [comment]
Hi, thanks for mentioning this. This is because the page cannot retrieve backend data successfully. There is a `content length mismatch` error in this page and I have no quick idea how to fix.  I'll merge the dev branch (that works) asap.
